### ISSUE TITLE
[BUG]: The tailwind image link in the skills area isn't there.

### ISSUE THREAD

**Issue by AryanBabber** [AliReza1083/Portfolio#7]
In the skills area, there is a small issue regarding the icon section of tailwind component which is not visible and the source link isn't showing up as well

When clicked on the image from the codebase:
![image](https://user-images.githubusercontent.com/86878236/209055845-dab250ec-1fcc-40ba-b394-1a8544979c40.png)

**Comment by AliReza1083** [comment]
I see, Thanks for letting me know.
Soon I'll make change my portfolio to a new one.

**Comment by AliReza1083** [comment]
Thank You Aryan
